# Generated by Django 6.0.7 on 2026-09-18 17:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('BUG', 'Bug'), ('SERVICE_REQUEST', 'Service Request'), ('ACCESS_REQUEST', 'Access Request'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('rule_type', models.CharField(choices=[('SUBJECT_PREFIX', 'Subject Prefix'), ('EXACT_PHRASE', 'Exact Phrase'), ('KEYWORD', 'Keyword'), ('FUZZY_KEYWORD', 'Fuzzy Keyword')], max_length=20)),
                ('pattern', models.CharField(max_length=200)),
                ('normalized_pattern', models.CharField(default='', editable=False, max_length=200)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('priority_order', models.PositiveSmallIntegerField(default=100)),
                ('is_system', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'classification_rule',
                'ordering': ['priority_order', '-score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleMappingRule',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword_or_phrase', models.CharField(max_length=200)),
                ('normalized_phrase', models.CharField(default='', editable=False, max_length=200)),
                ('score', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)])),
                ('priority_order', models.PositiveSmallIntegerField(default=100)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'module_mapping_rule',
                'ordering': ['priority_order', '-score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_subject', models.CharField(blank=True, default='', max_length=255)),
                ('original_body', models.TextField(blank=True, default='')),
                ('rule_predicted_type', models.CharField(blank=True, choices=[('BUG', 'Bug'), ('SERVICE_REQUEST', 'Service Request'), ('ACCESS_REQUEST', 'Access Request'), ('UNKNOWN', 'Unknown')], default='', max_length=20)),
                ('rule_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('matched_rules', models.JSONField(blank=True, default=list)),
                ('all_scores', models.JSONField(blank=True, default=dict)),
                ('review_reason', models.CharField(blank=True, default='', max_length=255)),
                ('human_final_type', models.CharField(blank=True, choices=[('BUG', 'Bug'), ('SERVICE_REQUEST', 'Service Request'), ('ACCESS_REQUEST', 'Access Request'), ('UNKNOWN', 'Unknown')], default='', max_length=20)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, db_column='corrected_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_corrections', to=settings.AUTH_USER_MODEL)),
                ('human_final_module', models.ForeignKey(blank=True, db_column='human_final_module_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.modulemaster')),
                ('human_final_project', models.ForeignKey(blank=True, db_column='human_final_project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.projectmaster')),
            ],
            options={
                'db_table': 'classification_audit',
                'ordering': ['-id'],
            },
        ),
    ]
