# Generated by Django 6.0.7 on 2026-09-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('mail_intake', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationaudit',
            name='mail',
            field=models.ForeignKey(db_column='mail_intake_id', on_delete=django.db.models.deletion.PROTECT, related_name='classification_audits', to='mail_intake.mailintake'),
        ),
        migrations.AddField(
            model_name='classificationaudit',
            name='rule_module',
            field=models.ForeignKey(blank=True, db_column='rule_module_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.modulemaster'),
        ),
        migrations.AddField(
            model_name='classificationaudit',
            name='rule_project',
            field=models.ForeignKey(blank=True, db_column='rule_project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.projectmaster'),
        ),
    ]
