# Generated by Django 6.0.7 on 2026-09-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0002_initial'),
        ('masters', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationaudit',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='ticket_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classification_audits', to='tickets.supportticket'),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['is_active', 'is_deleted', 'rule_type'], name='idx_clsrule_active_type'),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['ticket_type'], name='idx_clsrule_ticket_type'),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['ticket_type', 'rule_type', 'normalized_pattern'], name='idx_clsrule_pattern'),
        ),
        migrations.AddField(
            model_name='modulemappingrule',
            name='module',
            field=models.ForeignKey(blank=True, db_column='module_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapping_rules', to='masters.modulemaster'),
        ),
        migrations.AddField(
            model_name='modulemappingrule',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, related_name='mapping_rules', to='masters.projectmaster'),
        ),
        migrations.AddField(
            model_name='modulemappingrule',
            name='submodule',
            field=models.ForeignKey(blank=True, db_column='submodule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapping_rules', to='masters.submodulemaster'),
        ),
        migrations.AddIndex(
            model_name='classificationaudit',
            index=models.Index(fields=['rule_predicted_type', 'human_final_type'], name='idx_clsaudit_accuracy'),
        ),
        migrations.AddIndex(
            model_name='classificationaudit',
            index=models.Index(fields=['mail'], name='idx_clsaudit_mail'),
        ),
        migrations.AddIndex(
            model_name='classificationaudit',
            index=models.Index(fields=['created_at'], name='idx_clsaudit_created'),
        ),
        migrations.AddIndex(
            model_name='modulemappingrule',
            index=models.Index(fields=['is_active', 'is_deleted'], name='idx_maprule_active'),
        ),
        migrations.AddIndex(
            model_name='modulemappingrule',
            index=models.Index(fields=['normalized_phrase', 'project'], name='idx_maprule_phrase'),
        ),
    ]
