"""Attachments extracted from intake mail (spec 24).

Field names deliberately mirror bugs.BugAttachment (file_name, file_type) rather
than spec 24's original_file_name/mime_type, so that copying a mail attachment
onto a bug later is a field-for-field map and a shared download view can serve
both.
"""

import uuid

from django.db import models


class MailAttachment(models.Model):
    id = models.BigAutoField(primary_key=True)
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    mail = models.ForeignKey(
        "mail_intake.MailIntake", on_delete=models.PROTECT,
        related_name="attachments", db_column="mail_intake_id",
    )

    # Sanitised for display only. The sender's filename is never used to build a
    # path (spec 45); stored_file_name is a generated UUID.
    file_name = models.CharField(max_length=255)
    stored_file_name = models.CharField(max_length=255, blank=True, default="")
    file_path = models.CharField(max_length=500, blank=True, default="")
    # Sniffed from the leading bytes, never the part's declared Content-Type.
    file_type = models.CharField(max_length=100, blank=True, default="")
    file_extension = models.CharField(max_length=10, blank=True, default="")
    file_size = models.PositiveBigIntegerField(default=0)
    checksum_sha256 = models.CharField(max_length=64, blank=True, default="")

    content_id = models.CharField(max_length=255, blank=True, default="")
    is_inline = models.BooleanField(default=False)

    # Beyond spec 24. A rejected attachment still gets a row, with no bytes
    # stored: silently dropping it leaves a reviewer wondering why the mail
    # mentions a screenshot that is not there.
    is_rejected = models.BooleanField(default=False)
    rejection_reason = models.CharField(max_length=255, blank=True, default="")

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "mail_attachment"
        ordering = ["id"]
        # stored_file_name is a uuid4 hex plus extension, generated by the
        # attachment service, so collisions are not a practical concern and a
        # conditional unique constraint (needed to allow "" on rejected rows)
        # would be silently ignored by MariaDB anyway.
        indexes = [
            models.Index(fields=["mail"], name="idx_mailatt_mail"),
            models.Index(fields=["stored_file_name"], name="idx_mailatt_stored"),
        ]

    def __str__(self):
        return self.file_name
