# Generated by Django 6.0.7 on 2026-09-18 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_extension', models.CharField(blank=True, default='', max_length=10)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('content_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_inline', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mail_attachment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailIntake',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('references_header', models.TextField(blank=True, default='')),
                ('dedupe_key', models.CharField(max_length=64)),
                ('from_email', models.CharField(max_length=320)),
                ('from_name', models.CharField(blank=True, default='', max_length=150)),
                ('to_emails', models.JSONField(blank=True, default=list)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('reply_to_email', models.CharField(blank=True, default='', max_length=320)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_html_sanitized', models.TextField(blank=True, default='')),
                ('normalized_subject', models.CharField(blank=True, default='', max_length=500)),
                ('normalized_body', models.TextField(blank=True, default='')),
                ('body_hash', models.CharField(blank=True, default='', max_length=64)),
                ('raw_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('received_at', models.DateTimeField()),
                ('mailbox_folder', models.CharField(default='INBOX', max_length=100)),
                ('mailbox_address', models.CharField(blank=True, default='', max_length=320)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATING', 'Validating'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('THREAD_UPDATE', 'Thread Update'), ('READY_FOR_CLASSIFICATION', 'Ready for Classification'), ('CLASSIFIED', 'Classified'), ('NEEDS_REVIEW', 'Needs Review'), ('TICKET_CREATED', 'Ticket Created'), ('PROCESSING_FAILED', 'Processing Failed')], default='RECEIVED', max_length=30)),
                ('processing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, choices=[('NO_SENDER', 'No sender address'), ('INVALID_SENDER', 'Malformed sender address'), ('RECIPIENT_MISMATCH', 'Not addressed to the intake mailbox'), ('EMPTY_CONTENT', 'No subject or body'), ('AUTO_REPLY', 'Automatic reply'), ('BOUNCE', 'Delivery failure notification'), ('DUPLICATE', 'Already processed'), ('MESSAGE_TOO_LARGE', 'Message exceeds size limit'), ('ATTACHMENT_REJECTED', 'Attachment failed validation'), ('PARSE_ERROR', 'Message could not be parsed'), ('IMAP_ERROR', 'Mailbox connection problem'), ('STORAGE_ERROR', 'File storage problem'), ('DB_ERROR', 'Database problem'), ('UNEXPECTED_ERROR', 'Unexpected error')], default='', max_length=50)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_reply', models.BooleanField(default=False)),
                ('is_bounce', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_thread_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mail_intake',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MailProcessingHistory',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('VALIDATING', 'Validating'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('THREAD_UPDATE', 'Thread Update'), ('READY_FOR_CLASSIFICATION', 'Ready for Classification'), ('CLASSIFIED', 'Classified'), ('NEEDS_REVIEW', 'Needs Review'), ('TICKET_CREATED', 'Ticket Created'), ('PROCESSING_FAILED', 'Processing Failed')], default='', max_length=30)),
                ('to_status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATING', 'Validating'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('THREAD_UPDATE', 'Thread Update'), ('READY_FOR_CLASSIFICATION', 'Ready for Classification'), ('CLASSIFIED', 'Classified'), ('NEEDS_REVIEW', 'Needs Review'), ('TICKET_CREATED', 'Ticket Created'), ('PROCESSING_FAILED', 'Processing Failed')], max_length=30)),
                ('action', models.CharField(max_length=60)),
                ('remarks', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, choices=[('NO_SENDER', 'No sender address'), ('INVALID_SENDER', 'Malformed sender address'), ('RECIPIENT_MISMATCH', 'Not addressed to the intake mailbox'), ('EMPTY_CONTENT', 'No subject or body'), ('AUTO_REPLY', 'Automatic reply'), ('BOUNCE', 'Delivery failure notification'), ('DUPLICATE', 'Already processed'), ('MESSAGE_TOO_LARGE', 'Message exceeds size limit'), ('ATTACHMENT_REJECTED', 'Attachment failed validation'), ('PARSE_ERROR', 'Message could not be parsed'), ('IMAP_ERROR', 'Mailbox connection problem'), ('STORAGE_ERROR', 'File storage problem'), ('DB_ERROR', 'Database problem'), ('UNEXPECTED_ERROR', 'Unexpected error')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mail_processing_history',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
