# Generated by Django 6.0.7 on 2026-09-18 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail_intake', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailintake',
            name='linked_ticket',
            field=models.ForeignKey(blank=True, db_column='linked_ticket_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mails', to='tickets.supportticket'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='mail',
            field=models.ForeignKey(db_column='mail_intake_id', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='mail_intake.mailintake'),
        ),
        migrations.AddField(
            model_name='mailprocessinghistory',
            name='mail',
            field=models.ForeignKey(db_column='mail_intake_id', on_delete=django.db.models.deletion.PROTECT, related_name='processing_history', to='mail_intake.mailintake'),
        ),
        migrations.AddField(
            model_name='mailprocessinghistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_column='performed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mailintake',
            index=models.Index(fields=['processing_status', 'received_at'], name='idx_mail_status_recvd'),
        ),
        migrations.AddIndex(
            model_name='mailintake',
            index=models.Index(fields=['message_id'], name='idx_mail_message_id'),
        ),
        migrations.AddIndex(
            model_name='mailintake',
            index=models.Index(fields=['in_reply_to'], name='idx_mail_in_reply_to'),
        ),
        migrations.AddIndex(
            model_name='mailintake',
            index=models.Index(fields=['provider_thread_id'], name='idx_mail_thread_id'),
        ),
        migrations.AddIndex(
            model_name='mailintake',
            index=models.Index(fields=['from_email', 'received_at'], name='idx_mail_from_recvd'),
        ),
        migrations.AddIndex(
            model_name='mailintake',
            index=models.Index(fields=['linked_ticket'], name='idx_mail_linked_ticket'),
        ),
        migrations.AddIndex(
            model_name='mailintake',
            index=models.Index(fields=['received_at'], name='idx_mail_received_at'),
        ),
        migrations.AddConstraint(
            model_name='mailintake',
            constraint=models.UniqueConstraint(fields=('dedupe_key',), name='uq_mail_intake_dedupe_key'),
        ),
        migrations.AddIndex(
            model_name='mailattachment',
            index=models.Index(fields=['mail'], name='idx_mailatt_mail'),
        ),
        migrations.AddIndex(
            model_name='mailattachment',
            index=models.Index(fields=['stored_file_name'], name='idx_mailatt_stored'),
        ),
        migrations.AddIndex(
            model_name='mailprocessinghistory',
            index=models.Index(fields=['mail', '-created_at'], name='idx_mailph_mail_created'),
        ),
        migrations.AddIndex(
            model_name='mailprocessinghistory',
            index=models.Index(fields=['to_status', 'created_at'], name='idx_mailph_to_status'),
        ),
    ]
