# Generated by Django 6.0.7 on 2026-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_intake', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailintake',
            name='last_error_code',
            field=models.CharField(blank=True, choices=[('NO_SENDER', 'No sender address'), ('INVALID_SENDER', 'Malformed sender address'), ('RECIPIENT_MISMATCH', 'Not addressed to the intake mailbox'), ('EMPTY_CONTENT', 'No subject or body'), ('PROMOTIONAL_MAIL', 'Promotional mail'), ('NO_REPLY', 'No-reply sender'), ('AUTO_REPLY', 'Automatic reply'), ('BOUNCE', 'Delivery failure notification'), ('DUPLICATE', 'Already processed'), ('MESSAGE_TOO_LARGE', 'Message exceeds size limit'), ('ATTACHMENT_REJECTED', 'Attachment failed validation'), ('PARSE_ERROR', 'Message could not be parsed'), ('IMAP_ERROR', 'Mailbox connection problem'), ('STORAGE_ERROR', 'File storage problem'), ('DB_ERROR', 'Database problem'), ('UNEXPECTED_ERROR', 'Unexpected error')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailprocessinghistory',
            name='error_code',
            field=models.CharField(blank=True, choices=[('NO_SENDER', 'No sender address'), ('INVALID_SENDER', 'Malformed sender address'), ('RECIPIENT_MISMATCH', 'Not addressed to the intake mailbox'), ('EMPTY_CONTENT', 'No subject or body'), ('PROMOTIONAL_MAIL', 'Promotional mail'), ('NO_REPLY', 'No-reply sender'), ('AUTO_REPLY', 'Automatic reply'), ('BOUNCE', 'Delivery failure notification'), ('DUPLICATE', 'Already processed'), ('MESSAGE_TOO_LARGE', 'Message exceeds size limit'), ('ATTACHMENT_REJECTED', 'Attachment failed validation'), ('PARSE_ERROR', 'Message could not be parsed'), ('IMAP_ERROR', 'Mailbox connection problem'), ('STORAGE_ERROR', 'File storage problem'), ('DB_ERROR', 'Database problem'), ('UNEXPECTED_ERROR', 'Unexpected error')], default='', max_length=50),
        ),
    ]
