# Generated by Django 6.0.7 on 2026-09-18 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        ('mail_intake', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(editable=False, max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('EMAIL', 'Email')], default='MANUAL', max_length=20)),
                ('ticket_type', models.CharField(choices=[('BUG', 'Bug'), ('SERVICE_REQUEST', 'Service Request'), ('ACCESS_REQUEST', 'Access Request'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('classification_method', models.CharField(choices=[('MANUAL', 'Manual'), ('RULE_BASED', 'Rule Based'), ('AI', 'AI Assisted')], default='MANUAL', max_length=20)),
                ('classification_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('classification_status', models.CharField(choices=[('AUTO_CLASSIFIED', 'Auto Classified'), ('NEEDS_REVIEW', 'Needs Review'), ('HUMAN_CONFIRMED', 'Human Confirmed')], default='NEEDS_REVIEW', max_length=20)),
                ('classification_reason', models.TextField(blank=True, default='')),
                ('needs_review', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reported_by_email', models.CharField(blank=True, default='', max_length=320)),
                ('reported_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('NEEDS_REVIEW', 'Needs Review'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='NEW', max_length=25)),
                ('expected_closure_date', models.DateField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ack_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ack_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('bug', models.OneToOneField(blank=True, db_column='bug_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket', to='bugs.bug')),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_tickets', to=settings.AUTH_USER_MODEL)),
                ('mail_intake', models.ForeignKey(blank=True, db_column='mail_intake_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='mail_intake.mailintake')),
                ('module', models.ForeignKey(blank=True, db_column='module_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='masters.modulemaster')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tickets', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, db_column='priority_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='masters.prioritymaster')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='masters.projectmaster')),
                ('reported_by', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.PROTECT, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
                ('submodule', models.ForeignKey(blank=True, db_column='submodule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='masters.submodulemaster')),
            ],
            options={
                'db_table': 'support_ticket',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketNumberSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=4)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_number_sequence',
                'constraints': [models.UniqueConstraint(fields=('period',), name='uq_ticket_number_sequence_period')],
            },
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('update_text', models.TextField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('USER', 'User'), ('EMAIL', 'Email'), ('SYSTEM', 'System')], default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_updates', to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(blank=True, db_column='mail_intake_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_updates', to='mail_intake.mailintake')),
                ('ticket', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='tickets.supportticket')),
            ],
            options={
                'db_table': 'ticket_update',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('BUG', 'Bug'), ('SERVICE_REQUEST', 'Service Request'), ('ACCESS_REQUEST', 'Access Request'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('priority_order', models.PositiveSmallIntegerField(default=100)),
                ('is_system', models.BooleanField(default=False)),
                ('backup_assignee', models.ForeignKey(blank=True, db_column='backup_assignee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_assignment_rules', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, db_column='module_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='masters.modulemaster')),
                ('primary_assignee', models.ForeignKey(blank=True, db_column='primary_assignee_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_assignment_rules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='masters.projectmaster')),
                ('submodule', models.ForeignKey(blank=True, db_column='submodule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='masters.submodulemaster')),
                ('tester', models.ForeignKey(blank=True, db_column='tester_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tester_assignment_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_rule',
                'ordering': ['priority_order', 'id'],
                'indexes': [models.Index(fields=['ticket_type', 'is_active', 'is_deleted'], name='idx_assignrule_type'), models.Index(fields=['project', 'module', 'submodule'], name='idx_assignrule_scope')],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'is_deleted'], name='idx_ticket_status_del'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_type', 'status'], name='idx_ticket_type_status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['needs_review', 'created_at'], name='idx_ticket_review'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['owner', 'status'], name='idx_ticket_owner_status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['project', 'status'], name='idx_ticket_project_stat'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['mail_intake'], name='idx_ticket_mail_intake'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['reported_by_email'], name='idx_ticket_reporter_mail'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ack_message_id'], name='idx_ticket_ack_msg_id'),
        ),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.UniqueConstraint(fields=('ticket_no',), name='uq_support_ticket_ticket_no'),
        ),
        migrations.AddIndex(
            model_name='ticketupdate',
            index=models.Index(fields=['ticket', '-created_at'], name='idx_ticketupd_ticket'),
        ),
    ]
