# Generated by Django 6.0.7 on 2026-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_backfill_bug_support_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('IN_PERSON', 'In Person')], default='MANUAL', max_length=20),
        ),
    ]
