# Generated by Django 6.0.7 on 2026-09-21 16:35

from django.conf import settings
from django.db import migrations, models


def backfill_ref_no(apps, schema_editor):
    """Give every existing ticket an intake reference.

    Existing rows keep their TKT number -- they were already issued and the
    requester may hold it -- and gain a REF in the period they were created in,
    so the two series line up for anything created from here on. The ref
    sequence is left at the high-water mark per period, otherwise the next live
    allocation would collide with a backfilled row.
    """
    SupportTicket = apps.get_model("tickets", "SupportTicket")
    TicketRefSequence = apps.get_model("tickets", "TicketRefSequence")

    counters = {}
    rows = SupportTicket.objects.filter(ref_no="").order_by("id").only("id", "created_at")
    updates = []
    for ticket in rows.iterator(chunk_size=500):
        period = ticket.created_at.strftime("%y%m")
        counters[period] = counters.get(period, 0) + 1
        ticket.ref_no = f"REF-{period}-{counters[period]:04d}"
        updates.append(ticket)
        if len(updates) >= 500:
            SupportTicket.objects.bulk_update(updates, ["ref_no"])
            updates = []
    if updates:
        SupportTicket.objects.bulk_update(updates, ["ref_no"])

    for period, last in counters.items():
        TicketRefSequence.objects.update_or_create(
            period=period, defaults={"last_number": last},
        )


def clear_ref_no(apps, schema_editor):
    apps.get_model("tickets", "SupportTicket").objects.update(ref_no="")
    apps.get_model("tickets", "TicketRefSequence").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_bug_environment_alter_bug_priority_and_more'),
        ('mail_intake', '0002_initial'),
        ('masters', '0001_initial'),
        ('tickets', '0004_alter_supportticket_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRefSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=4)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_ref_sequence',
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ref_no',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_no',
            field=models.CharField(blank=True, default=None, editable=False, max_length=20, null=True),
        ),
        # Must run before the unique constraint: every row still holds "".
        migrations.RunPython(backfill_ref_no, clear_ref_no),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.UniqueConstraint(fields=('ref_no',), name='uq_support_ticket_ref_no'),
        ),
        migrations.AddConstraint(
            model_name='ticketrefsequence',
            constraint=models.UniqueConstraint(fields=('period',), name='uq_ticket_ref_sequence_period'),
        ),
    ]
