# Generated by Django 6.0.7 on 2026-09-21 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_ticket_ref_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('ticket', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tickets.supportticket')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_attachments',
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['ticket', 'is_deleted'], name='idx_tktatt_tkt_deleted')],
                'constraints': [models.UniqueConstraint(fields=('stored_file_name',), name='uq_ticket_attach_stored_name')],
            },
        ),
    ]
