# Generated by Django 6.0.7 on 2026-09-28 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_work_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('NEEDS_REVIEW', 'Needs Review'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('ON_HOLD', 'On Hold'), ('TESTING', 'Testing / Verification'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='NEW', max_length=25),
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=40)),
                ('actor_type', models.CharField(default='SYSTEM', max_length=20)),
                ('actor_email', models.CharField(blank=True, default='', max_length=320)),
                ('actor_display_name', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('public_description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='tickets.supportticket')),
            ],
            options={
                'db_table': 'ticket_activity',
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['ticket', 'occurred_at'], name='idx_tact_ticket_time')],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('from_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments_from', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='tickets.supportticket')),
                ('to_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_assignment_history',
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['ticket', '-performed_at'], name='idx_tassign_ticket_time')],
            },
        ),
        migrations.CreateModel(
            name='TicketChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_type', models.CharField(max_length=20)),
                ('sender_email', models.CharField(blank=True, default='', max_length=320)),
                ('sender_display_name', models.CharField(max_length=150)),
                ('message_text', models.TextField()),
                ('is_system_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hidden_ticket_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketchatmessage')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to='tickets.supportticket')),
            ],
            options={
                'db_table': 'ticket_chat_message',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='idx_tchat_ticket_time')],
            },
        ),
        migrations.CreateModel(
            name='TicketReopenHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requester_email', models.CharField(max_length=320)),
                ('reason', models.TextField()),
                ('previous_status', models.CharField(max_length=25)),
                ('reopened_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopen_history', to='tickets.supportticket')),
            ],
            options={
                'db_table': 'ticket_reopen_history',
                'ordering': ['-reopened_at', '-id'],
                'indexes': [models.Index(fields=['ticket', '-reopened_at'], name='idx_treopen_ticket_time')],
            },
        ),
    ]
