# Generated by Django 6.0.7 on 2026-09-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_supportticket_status_ticketactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('NEEDS_REVIEW', 'Needs Review'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('REOPENED', 'Reopened'), ('PENDING', 'Pending'), ('ON_HOLD', 'On Hold'), ('TESTING', 'Testing / Verification'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='NEW', max_length=25),
        ),
    ]
