# Generated by Django 6.0.7 on 2026-09-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_supportticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatmessage',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticketchatmessage',
            name='starred_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TicketChatRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_text', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='tickets.ticketchatmessage')),
            ],
            options={
                'db_table': 'ticket_chat_revision',
            },
        ),
    ]
