# Generated by Django 6.0.7 on 2026-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketchatmessage_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchatmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
