# Generated by Django 6.0.7 on 2026-09-14 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bug_no', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reported_date', models.DateField()),
                ('environment', models.CharField(choices=[('PRODUCTION', 'Production'), ('UAT', 'UAT'), ('STAGING', 'Staging'), ('DEVELOPMENT', 'Development'), ('LOCAL', 'Local')], default='PRODUCTION', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], default='NEW', max_length=20)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('expected_closure_date', models.DateField(blank=True, null=True)),
                ('latest_remarks', models.TextField(blank=True, default='')),
                ('latest_update_at', models.DateTimeField(blank=True, null=True)),
                ('latest_update_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('hold_reason', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('verification_result', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Passed')], default='', max_length=20)),
                ('verification_remarks', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('closure_remarks', models.TextField(blank=True, default='')),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_count', models.PositiveIntegerField(default=0)),
                ('last_reopened_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, db_column='closed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_bugs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.departmentmaster')),
                ('module', models.ForeignKey(blank=True, db_column='module_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.modulemaster')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_bugs', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(db_column='priority_id', on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.prioritymaster')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.projectmaster')),
                ('reported_by', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.PROTECT, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_column='resolved_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_bugs', to=settings.AUTH_USER_MODEL)),
                ('root_cause_type', models.ForeignKey(blank=True, db_column='root_cause_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.rootcausetypemaster')),
                ('severity', models.ForeignKey(db_column='severity_id', on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.severitymaster')),
                ('site', models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.sitemaster')),
                ('submodule', models.ForeignKey(blank=True, db_column='submodule_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.submodulemaster')),
                ('tested_by', models.ForeignKey(blank=True, db_column='tested_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tested_bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_tracker',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BugAssignmentHistory',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(db_column='assigned_by', on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(db_column='bug_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='bugs.bug')),
                ('from_owner', models.ForeignKey(blank=True, db_column='from_owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_from', to=settings.AUTH_USER_MODEL)),
                ('to_owner', models.ForeignKey(blank=True, db_column='to_owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_assignment_history',
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BugReopenHistory',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reopen_reason', models.TextField()),
                ('reopened_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(db_column='bug_id', on_delete=django.db.models.deletion.PROTECT, related_name='reopen_history', to='bugs.bug')),
                ('reopened_by', models.ForeignKey(db_column='reopened_by', on_delete=django.db.models.deletion.PROTECT, related_name='reopened_bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_reopen_history',
                'ordering': ['-reopened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BugStatusHistory',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], default='', max_length=20)),
                ('to_status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(db_column='bug_id', on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='bugs.bug')),
                ('changed_by', models.ForeignKey(db_column='changed_by', on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_status_history',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BugTestingHistory',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_result', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('test_remarks', models.TextField(blank=True, default='')),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(db_column='bug_id', on_delete=django.db.models.deletion.PROTECT, related_name='testing_history', to='bugs.bug')),
                ('tested_by', models.ForeignKey(db_column='tested_by', on_delete=django.db.models.deletion.PROTECT, related_name='test_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_testing_history',
                'ordering': ['-tested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BugUpdate',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], max_length=20)),
                ('update_text', models.TextField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateField(db_index=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('bug', models.ForeignKey(db_column='bug_id', on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='bugs.bug')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bug_updates_as_owner', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', on_delete=django.db.models.deletion.PROTECT, related_name='authored_bug_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_updates',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BugAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('context', models.CharField(choices=[('BUG', 'Bug'), ('UPDATE', 'Daily Update'), ('TESTING', 'Testing'), ('CLOSURE', 'Closure')], default='BUG', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('bug', models.ForeignKey(db_column='bug_id', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='bugs.bug')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('bug_update', models.ForeignKey(blank=True, db_column='bug_update_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='bugs.bugupdate')),
            ],
            options={
                'db_table': 'bug_attachments',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['status', 'is_deleted'], name='idx_bug_status_deleted'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['owner', 'status'], name='idx_bug_owner_status'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['project', 'status'], name='idx_bug_project_status'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['module', 'status'], name='idx_bug_module_status'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['priority', 'status'], name='idx_bug_priority_status'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['severity', 'status'], name='idx_bug_severity_status'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['reported_by'], name='idx_bug_reported_by'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['expected_closure_date', 'status'], name='idx_bug_expected_status'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['reported_date'], name='idx_bug_reported_date'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['closed_date'], name='idx_bug_closed_date'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['resolved_date'], name='idx_bug_resolved_date'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['status', 'latest_update_date', 'owner'], name='idx_bug_update_pending'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['bug_no'], name='idx_bug_no'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['title'], name='idx_bug_title'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['root_cause_type'], name='idx_bug_root_cause_type'),
        ),
        migrations.AddConstraint(
            model_name='bug',
            constraint=models.UniqueConstraint(fields=('bug_no',), name='uq_bug_tracker_bug_no'),
        ),
        migrations.AddIndex(
            model_name='bugassignmenthistory',
            index=models.Index(fields=['bug', '-assigned_at'], name='idx_bugah_bug_assigned'),
        ),
        migrations.AddIndex(
            model_name='bugassignmenthistory',
            index=models.Index(fields=['to_owner'], name='idx_bugah_to_owner'),
        ),
        migrations.AddIndex(
            model_name='bugreopenhistory',
            index=models.Index(fields=['bug', '-reopened_at'], name='idx_bugrh_bug_reopened'),
        ),
        migrations.AddIndex(
            model_name='bugreopenhistory',
            index=models.Index(fields=['reopened_at'], name='idx_bugrh_reopened_at'),
        ),
        migrations.AddIndex(
            model_name='bugstatushistory',
            index=models.Index(fields=['bug', '-changed_at'], name='idx_bugsh_bug_changed'),
        ),
        migrations.AddIndex(
            model_name='bugstatushistory',
            index=models.Index(fields=['to_status', 'changed_at'], name='idx_bugsh_to_status'),
        ),
        migrations.AddIndex(
            model_name='bugtestinghistory',
            index=models.Index(fields=['bug', '-tested_at'], name='idx_bugth_bug_tested'),
        ),
        migrations.AddIndex(
            model_name='bugtestinghistory',
            index=models.Index(fields=['test_result'], name='idx_bugth_result'),
        ),
        migrations.AddIndex(
            model_name='bugupdate',
            index=models.Index(fields=['bug', '-created_at'], name='idx_bugupd_bug_created'),
        ),
        migrations.AddIndex(
            model_name='bugupdate',
            index=models.Index(fields=['update_date', 'updated_by'], name='idx_bugupd_date_user'),
        ),
        migrations.AddIndex(
            model_name='bugupdate',
            index=models.Index(fields=['bug', 'update_date'], name='idx_bugupd_bug_date'),
        ),
        migrations.AddIndex(
            model_name='bugattachment',
            index=models.Index(fields=['bug', 'is_deleted'], name='idx_bugatt_bug_deleted'),
        ),
        migrations.AddIndex(
            model_name='bugattachment',
            index=models.Index(fields=['bug_update'], name='idx_bugatt_update'),
        ),
        migrations.AddConstraint(
            model_name='bugattachment',
            constraint=models.UniqueConstraint(fields=('stored_file_name',), name='uq_bug_attach_stored_name'),
        ),
    ]
