# Generated by Django 6.0.7 on 2026-09-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='environment',
            field=models.CharField(blank=True, choices=[('PRODUCTION', 'Production'), ('UAT', 'UAT'), ('STAGING', 'Staging'), ('DEVELOPMENT', 'Development'), ('LOCAL', 'Local')], default='PRODUCTION', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.ForeignKey(blank=True, db_column='priority_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.prioritymaster'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.projectmaster'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reported_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.ForeignKey(blank=True, db_column='severity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='masters.severitymaster'),
        ),
    ]
