# Generated by Django 6.0.7 on 2026-09-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_bug_environment_alter_bug_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='pending_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugstatushistory',
            name='to_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bugupdate',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('TESTING', 'Testing / Verification'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected / Not a Bug')], max_length=20),
        ),
    ]
