# Generated by Django 6.0.7 on 2026-09-14 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_unique_id', models.UUIDField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=120)),
                ('action', models.CharField(choices=[('BUG_CREATED', 'Bug Created'), ('BUG_UPDATED', 'Bug Updated'), ('ASSIGN', 'Assigned'), ('REASSIGN', 'Reassigned'), ('STATUS_CHANGE', 'Status Changed'), ('PRIORITY_CHANGE', 'Priority Changed'), ('SEVERITY_CHANGE', 'Severity Changed'), ('EXPECTED_CLOSURE_CHANGE', 'Expected Closure Changed'), ('UPDATE_ADDED', 'Daily Update Added'), ('ROOT_CAUSE_UPDATE', 'Root Cause Updated'), ('RESOLUTION_UPDATE', 'Resolution Updated'), ('TESTING_RESULT', 'Testing Result Recorded'), ('RESOLVED', 'Resolved'), ('CLOSURE', 'Closed'), ('REOPEN', 'Reopened'), ('REJECTED', 'Rejected'), ('ATTACHMENT_UPLOAD', 'Attachment Uploaded'), ('ATTACHMENT_DELETE', 'Attachment Deleted'), ('ATTACHMENT_DOWNLOAD', 'Attachment Downloaded'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('ROLE_UPDATED', 'Role Updated'), ('PERMISSION_CHANGED', 'Permissions Changed'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed')], max_length=40)),
                ('field_name', models.CharField(blank=True, default='', max_length=60)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('performed_by', models.ForeignKey(blank=True, db_column='performed_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity'), models.Index(fields=['action', 'performed_at'], name='idx_audit_action_time'), models.Index(fields=['performed_by', 'performed_at'], name='idx_audit_user_time'), models.Index(fields=['performed_at'], name='idx_audit_time')],
            },
        ),
    ]
