# Generated by Django 6.0.7 on 2026-09-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('BUG_CREATED', 'Bug Created'), ('BUG_UPDATED', 'Bug Updated'), ('ASSIGN', 'Assigned'), ('REASSIGN', 'Reassigned'), ('STATUS_CHANGE', 'Status Changed'), ('PRIORITY_CHANGE', 'Priority Changed'), ('SEVERITY_CHANGE', 'Severity Changed'), ('EXPECTED_CLOSURE_CHANGE', 'Expected Closure Changed'), ('UPDATE_ADDED', 'Daily Update Added'), ('ROOT_CAUSE_UPDATE', 'Root Cause Updated'), ('RESOLUTION_UPDATE', 'Resolution Updated'), ('TESTING_RESULT', 'Testing Result Recorded'), ('RESOLVED', 'Resolved'), ('CLOSURE', 'Closed'), ('REOPEN', 'Reopened'), ('REJECTED', 'Rejected'), ('ATTACHMENT_UPLOAD', 'Attachment Uploaded'), ('ATTACHMENT_DELETE', 'Attachment Deleted'), ('ATTACHMENT_DOWNLOAD', 'Attachment Downloaded'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('USER_PASSWORD_RESET', 'Password Reset by Admin'), ('USER_ROLES_CHANGED', 'User Roles Changed'), ('ROLE_UPDATED', 'Role Updated'), ('PERMISSION_CHANGED', 'Permissions Changed'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed')], max_length=40),
        ),
    ]
