# Generated by Django 6.0.7 on 2026-09-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('BUG_CREATED', 'Bug Created'), ('BUG_UPDATED', 'Bug Updated'), ('ASSIGN', 'Assigned'), ('REASSIGN', 'Reassigned'), ('STATUS_CHANGE', 'Status Changed'), ('PRIORITY_CHANGE', 'Priority Changed'), ('SEVERITY_CHANGE', 'Severity Changed'), ('EXPECTED_CLOSURE_CHANGE', 'Expected Closure Changed'), ('UPDATE_ADDED', 'Daily Update Added'), ('ROOT_CAUSE_UPDATE', 'Root Cause Updated'), ('RESOLUTION_UPDATE', 'Resolution Updated'), ('TESTING_RESULT', 'Testing Result Recorded'), ('RESOLVED', 'Resolved'), ('CLOSURE', 'Closed'), ('REOPEN', 'Reopened'), ('REJECTED', 'Rejected'), ('ATTACHMENT_UPLOAD', 'Attachment Uploaded'), ('ATTACHMENT_DELETE', 'Attachment Deleted'), ('ATTACHMENT_DOWNLOAD', 'Attachment Downloaded'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('USER_PASSWORD_RESET', 'Password Reset by Admin'), ('USER_ROLES_CHANGED', 'User Roles Changed'), ('ROLE_UPDATED', 'Role Updated'), ('PERMISSION_CHANGED', 'Permissions Changed'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('MAIL_RECEIVED', 'Mail Received'), ('MAIL_REJECTED', 'Mail Rejected'), ('MAIL_DUPLICATE', 'Mail Duplicate Ignored'), ('MAIL_THREAD_LINKED', 'Mail Linked to Ticket Thread'), ('MAIL_CLASSIFIED', 'Mail Classified'), ('MAIL_CLASSIFICATION_CORRECTED', 'Mail Classification Corrected'), ('MAIL_CLASSIFICATION_CONFIRMED', 'Mail Classification Confirmed'), ('MAIL_REPROCESSED', 'Mail Reprocessed'), ('MAIL_IGNORED', 'Mail Ignored'), ('MAIL_ACK_SENT', 'Acknowledgement Sent'), ('TICKET_CREATED_FROM_EMAIL', 'Ticket Created from Email'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_TYPE_CHANGED', 'Ticket Type Changed'), ('MODULE_MAPPING_CHANGED', 'Module Mapping Changed'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_UPDATE_ADDED', 'Ticket Update Added'), ('ACCESS_APPROVED', 'Access Request Approved'), ('ACCESS_REJECTED', 'Access Request Rejected'), ('ACCESS_IMPLEMENTED', 'Access Change Implemented'), ('CLASSIFICATION_RULE_CHANGED', 'Classification Rule Changed')], max_length=40),
        ),
    ]
