# Generated by Django 6.0.7 on 2026-09-14 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('BUG_ASSIGNED', 'Bug Assigned to You'), ('PRIORITY_CRITICAL', 'Priority Changed to Critical'), ('EXPECTED_CLOSURE_CHANGED', 'Expected Closure Changed'), ('MOVED_TO_TESTING', 'Bug Moved to Testing'), ('TEST_FAILED', 'Test Failed'), ('BUG_REOPENED', 'Bug Reopened'), ('BUG_OVERDUE', 'Bug Overdue'), ('UPDATE_PENDING', 'Daily Update Pending')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(blank=True, db_column='bug_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bugs.bug')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_recipient'), models.Index(fields=['bug'], name='idx_notif_bug')],
            },
        ),
    ]
